name: Datastax Gallery Loader
run-name: ${{ github.actor }} is populating 🚀
on: [push]
jobs:
  Update-app-gallery:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: python --version
      - run: cd ${{ github.workspace }}
      - run: echo "ASTRA_DB_APPLICATION_TOKEN=${{ secrets.ASTRA_DB_APPLICATION_TOKEN }}" > .env
      - run: echo "ASTRA_DB_API_ENDPOINT=${{ secrets.ASTRA_DB_API_ENDPOINT }}" >> .env
      - run: echo "GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}" >> .env
      - run: echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> .env
      - run: echo ${{secrets.CREDENTIALS_JSON}}
      - run: echo '${{secrets.CREDENTIALS_JSON}}' | base64 --decode | jq > credentials.json
      - run: echo '${{secrets.TOKEN_JSON}}' | base64 -- decode | jq > token.json
      - run: jq
      - run: cat token.json
      - run: cat credentials.json
      - run: ls -al
      - run: pip install -r requirements.txt
      - run: python getAppData.py
