name: Datastax Gallery Loader
run-name: ${{ github.actor }} is populating 🚀
on: [push]
jobs:
  Update-app-gallery:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: python --version
      - run: cd ${{ github.workspace }}
      - run: pip install -r requirements.txt
      - run: echo "ASTRA_DB_APPLICATION_TOKEN=" + ${{ secrets.ASTRA_DB_APPLICATION_TOKEN }} > .env
      - run: echo "ASTRA_DB_API_ENDPOINT=" + ${{ secrets.ASTRA_DB_API_ENDPOINT }} >> .env
      - run: echo "GH_TOKEN=" + ${{ secrets.GH_TOKEN }} >> .env
      - run: cat .env
      - run: python getAppData.py
