name: Datastax Gallery Loader
run-name: ${{ github.actor }} is populating 🚀
on: [push]
jobs:
  Update-app-gallery:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: python --version
      - run: cd ${{ github.workspace }}
      - run: pip install -r requirements.txt
      - run: echo '${{ secrets.TOKEN_JSON }}' | openssl base64 -d
      - run: echo '${{ secrets.CREDENTIALS_JSON }}' | openssl base64 -d
      - run: echo "ASTRA_DB_APPLICATION_TOKEN=${{ secrets.ASTRA_DB_APPLICATION_TOKEN }}" >> .env
      - run: echo "ASTRA_DB_API_ENDPOINT=${{ secrets.ASTRA_DB_API_ENDPOINT }}" >> .env
      - run: echo "GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}" >> .env
      - run: echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> .env
      - run: cat .env
      - run: python getAppData.py
      - uses: stefanzweifel/git-auto-commit-action@v5
      - run: echo "Updated app gallery now"
