name: GitHub Actions Demo
run-name: ${{ github.actor }} is populating 🚀
on: [push]
jobs:
  Update-app-gallery:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: python --version
      - run: cd ${{ github.workspace }}
      - run: pip install -r requirements.txt
      - run: python getAppData.py
